policy:
  approval:
  - or:
    - has auto-merge label
    - and:
      - or:
        - the maintainers-frontend team has approved
        - an admin has approved
      - the HCF team has approved
      - the ZAN team has approved
      - the ZDV team has approved
      - the ZLC team has approved

approval_rules:
  - name: the maintainers-frontend team has approved
    options:
      request_review:
        enabled: true
        mode: teams
      methods:
        comments:
          - "LGTM"
          - "/lgtm"
    requires:
      count: 1
      teams:
      - "adh-partnership/maintainers-frontend"
  - name: the HCF team has approved
    if:
      changed_files:
        paths:
          - "src/facilities/hcf/.*"
          - "src/facility-hcf.ts"
    options:
      request_review:
        enabled: true
        mode: teams
      methods:
        comments:
          - "LGTM"
          - "/lgtm"
    requires:
      count: 1
      teams:
      - "adh-partnership/hcf"
      - "adh-partnership/maintainers-frontend"
  - name: the ZAN team has approved
    if:
      changed_files:
        paths:
          - "src/facilities/zan/.*"
          - "src/facility-zan.ts"
    options:
      request_review:
        enabled: true
        mode: teams
      methods:
        comments:
          - "LGTM"
          - "/lgtm"
    requires:
      count: 1
      teams:
      - "adh-partnership/zan"
      - "adh-partnership/maintainers-frontend"
  - name: the ZDV team has approved
    if:
      changed_files:
        paths:
          - "src/facilities/zdv/.*"
          - "src/facility-zdv.ts"
    options:
      request_review:
        enabled: true
        mode: teams
      methods:
        comments:
          - "LGTM"
          - "/lgtm"
    requires:
      count: 1
      teams:
      - "adh-partnership/zdv"
      - "adh-partnership/maintainers-frontend"
  - name: the ZLC team has approved
    if:
      changed_files:
        paths:
          - "src/facilities/zlc/.*"
          - "src/facility-zlc.ts"
    options:
      request_review:
        enabled: true
        mode: teams
      methods:
        comments:
          - "LGTM"
          - "/lgtm"
    requires:
      count: 1
      teams:
      - "adh-partnership/zlc"
      - "adh-partnership/maintainers-frontend"
  - name: an admin has approved
    options:
      allow_author: true
      allow_contributor: true
      methods:
        comments:
          - "LGTM"
          - "/lgtm"
    requires:
      count: 1
      teams:
      - "adh-partnership/admin"
  - name: has auto-merge label
    if:
      has_labels:
      - "auto-merge"
      has_author_in:
        users: ["adh-bot"]
