name: Cherrypick

on:
  pull_request:
    types: ["closed", "labeled"]

jobs:
  cherrypick:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Cherrypick(s)
        id: cherrypick
        run: |
          labels=($(jq -r '.pull_request.labels | map(.name) | join(" ")' "$GITHUB_EVENT_PATH") )
          for label in "${labels[@]}"; do
            if [[ $label == cherrypick/* ]]; then
              gh workflow run run-cherrypick.yaml -f branch="release-${label#cherrypick/}" -f pr="${{ github.event.pull_request.number }}" -f title="${{ github.event.pull_request.title }}" -f author="${{ github.event.pull_request.user.login }}"
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.ADH_BOT_TOKEN }}
      - name: Create issue on failure
        if: ${{ failure() }}
        uses: dacbd/create-issue-action@main
        id: failed-issue
        with:
          token: ${{ secrets.ADH_BOT_TOKEN }}
          assignees: ${{ github.event.pull_request.user.login }}
          title: Cherrypick failed for PR ${{ github.event.pull_request.number }}
          body: |
            Failed to run cherrypick workflows. For more information, see the GitHub Action log at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.
