name: Trigger Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to tag (blank will auto-generate)'
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"
          token: ${{ secrets.ADH_BOT_TOKEN }}
      - name: Tag Release
        env:
          GITHUB_TOKEN: ${{ secrets.ADH_BOT_TOKEN }}
        run: |
          git config --global user.name "adh-bot"
          git config --global user.email "dhawton+adh@gmail.com"
          git fetch --tags

          set -ex
          version=${{ github.event.inputs.version }}
          if [ -z "$version" ]; then
            previous_tag=$(git tag --sort=-creatordate | head -n 1)
            version=$(echo $previous_tag | awk -F. -v OFS=. '{$2++;print $1,$2}')
          fi
          # Append epoch and build number to version
          version="${version}.$(date +%s).${{ github.run_number }}"

          echo "Version: $version"

          # Tag the release
          git tag "$version"
          git push origin "$version"

          # Increment version in .env
          new_version=$(echo $version | awk -F. -v OFS=. '{$2++;print $1,$2}')
          git checkout -b "bump-version-$new_version"
          # Check if .version already has new_version (strip newline)
          if [ "$(cat .version | tr -d '\n')" == "${new_version}.0-dev*" ]; then
            echo "Version already bumped to $new_version"
            exit 0
          fi
          echo "${new_version}.0-dev" > .version
          git add .version
          git commit -m "Increment dev version to $new_version"
          git push origin "bump-version-$new_version"
          gh pr create -t "Bump version to $new_version" -b "Bump version to $new_version" -B "main" -l "dependencies" -l "auto-merge"
          echo "Created PR to bump version to $new_version"

